### ISSUE TITLE
A better rewarding system

### ISSUE THREAD

**Issue by Alon-L** [Keyma-sh/game-tracker#139]
**Is your feature request related to a problem? Please describe.**
Typing websites lack a way of motivating players to continue playing the game, for hours on hours, nonstop.
A good fix, that most games implement, is a well-planned rewarding system, that encourages players to get better and play more.

**Describe the solution you'd like**
I'm aware that there is currently a coins system where players are able to buy minor customization items. However, I don't think it's enough.

TypeRacer has a competitions system, which awards players shiny medals shown publicly on their profile.
Those medals motivate a lot of players to keep playing for an absurd number of hours per day.

Another good example is the game Overwatch. The game awards players with a new level border for every 100 levels they surpass. It also lets players use a special currency for purchasing shiny rare golden weapons to use in-game, which motivates players to keep playing every season and gain those points.

I think that Keymash should implement some of the rewarding systems mentioned, and more unique ones, to keep players excited about playing on the website.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by CameronCT** [comment]
Fineeeee I'll add it.

**Comment by CameronCT** [comment]
Started.

**Comment by CameronCT** [comment]
I currently have a Points system implemented, however I have no where to really put this where it would make sense and could implement a design that explains the purpose of it.

My new proposal for this idea is to do A/B randomizing on swapping out the Average WPM daily ladder for an Activity daily ladder instead. This also rewards the players because the "Tournaments" tab will show their placing, and I got Aevi to design some top 3 badges that we could also fill in with this that will still offer the "rewarding" aspects of the game.

I am going to keep the code for the points implementation for a later date (in the event that the feedback on this ladder doesn't do well) however at this point it exists and can be implemented for the most part.
