### ISSUE TITLE
Leaderboards in LB tab does not update past 525

### ISSUE THREAD

**Issue by Syndric** [Keyma-sh/game-tracker#160]
**Describe the bug**
The profiles of people in all LB categories will not update past 525th place

**To Reproduce**
LB tab > go to place 525 in any category > go to the next page of leaderboards. When the next page of places is loaded, the numbers change so that 525 will become 550 but the people in the places do not change.

**Expected behavior**
Either the forward should disappear at a certain number if LBs need to be capped or LBs should keep generating

**Desktop (please complete the following information):**
macOS Big Sur
Chrome Version 96.0.4664.55 (Official Build) (x86_64)

**Comment by CameronCT** [comment]
Leaderboards have been capped since last update, therefore this is expected behavior. Of course the Next button should be disabled.

With the current limits, the leaderboards can hit a maximum of a hardcap `skip` of 500 however depending on the leaderboards the hard cap could actually stop at 500-550 results.

The "Next" button has been patched in the NextJS migration.
