### ISSUE TITLE
Learning Center Numbers results don't show when you make no mistakes

### ISSUE THREAD

**Issue by OctahedronV2** [Keyma-sh/game-tracker#24]
**Describe the bug**
When doing the first level of the numbers section of the learning center and making no mistakes, it shows all the results as 0 as well as saying "0ss" and "0%%" accuracy

**To Reproduce**
1. Go to learning center
2. Click Numbers
3. Click "Pi Basic"
4. Type in 3.14 while making no mistakes

**Expected behavior**
It should properly display the results

**Screenshots**
![image](https://user-images.githubusercontent.com/40345761/119194418-05f52000-ba51-11eb-8e5f-d6e69a23bbf0.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Opera GX
 - Version: 75.0.3969.259

**Comment by CameronCT** [comment]
This will be fixed next update (server restart update), however, I will note one additional issue with Learning 
(and that's because I'm trying to reconfigure the error/mistake bug that you actually reported a month or so back now)

The learning center is moved to validation by Keystroke, which means Mistakes will be based off keystrokes. Over the next bit we're going to try to re-create the text validation system both server and client-side and then transfer it to the actual gameplay that way we can offer much better accuracy statistics rather than rely on single word mistakes.
