### ISSUE TITLE
Playing in the stenography universe does not contribute to playtime, wins, achievements.  Nor do any stats count towards the stats provided in bot-commands discord

### ISSUE THREAD

**Issue by nathannguyen650** [Keyma-sh/game-tracker#65]
**Describe the bug**
Title.  For example, Aerick doesn't even have a minute of "playtime" or has even achieved 10 wpm.  

**To Reproduce**
Make a new account.  Play in stenography universe.  Notice you don't have any achievements.  

**Expected behavior**
Stats should increase

**Screenshots**

**Desktop (please complete the following information):**
windows 10
chrome

**Additional context**

**Comment by CameronCT** [comment]
Achievements aren't world based unfortunately and they likely never will be as it could promote people to "double" EXP by using the stenography realm. However the rest is fairly accurate here, in v2 I already have this patched for ya :)

The only thing I don't have added right now, is Tournament support but that is mainly due to the fact that steno is still too small of a footprint to need one.
