### ISSUE TITLE
Format Options

### ISSUE THREAD

**Issue by DotMatrixMoe** [Keyma-sh/game-tracker#72]
Being so used to Typeracer, perhaps having a format toolbar would be useful? I imagine being able to change the font size and text color. This may also help players who are colorblind and/or have optical disabilities.

**Comment by CameronCT** [comment]
This issue is mainly a request for more customization on the match stuff. In v2 there will be a new settings panel (which is also incredibly easier for me to add new features to it thankfully) so I will close this issue since this is requesting a toolbar. 

However, there will be new customization soon, I spent a long time revamping the Settings area so it can be a lot easier for me to add customizations.
