### ISSUE TITLE
Inaccurate accuracy in Learning Center

### ISSUE THREAD

**Issue by cyan-amethyst** [Keyma-sh/game-tracker#77]
**Describe the bug**
Making a typo on the very first word doesn't affect accuracy %, but accuracy calculation works just fine on any of the following words.

**To Reproduce**
1. Go to any lesson within the Learning Center
2. Make a mistake on the first word (whether wrong letter or accidentally pressing space)
3. Notice that the accuracy is still at 100%

**Expected behavior**
The accuracy should decrease accordingly.

**Screenshots**
![accurate](https://user-images.githubusercontent.com/87863597/126916158-13cf2229-5255-4dfe-9e62-2b994c1953e9.PNG)
![inaccurate](https://user-images.githubusercontent.com/87863597/126916161-c4937fec-25bd-4974-adfd-e76051ac5757.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Opera GX  //  Mozilla Firefox
 - Version: LVL 3 (core: 77.0.4054.275)  //  90.0.2

**Additional context.**
I mentioned both of the browsers in which I've seen this issue occur.

**Comment by CameronCT** [comment]
Confirmed issue.

**Comment by CameronCT** [comment]
So, this issue is technically confirmed but the Accuracy isn't wrong. It just doesn't update until you pass the word itself

1) Learning centre used to only do Accuracy based on word mistakes rather than keystroke mistakes, Keyma.sh does this in regular gameplay due to complaints of how people always get 90+ accuracy on TypeRacer (which by the way, is also inaccurate). So we moved to making it based off word mistakes to make accuracies seem more accurate and so people don't tell me that the game is inacurate because TypeRacer does X.

2) For numbers, they are the only course that bases mistakes off of keystrokes (since the text is usually only one word anyways) which makes it a bit different.

I would like to start using Keystrokes globally for accuracy (as that's how it should be). One problem that Keyma.sh has while doing keystrokes is that when people backspace on letters it will register it as a mistake since it's not matching the character for that specific word anymore. 

Keeping this issue open, as I should just address this issue and just make it disregard any validations when backspacing.

**Comment by CameronCT** [comment]
While this is still being tested in v2, I have recreated how keystrokes are validated in actual public Gameplay. For the Learning center though, the validation is fine minus the fact that it doesn't update on the first words which is normal for numbers as for the reasons mentioned above.
