### ISSUE TITLE
Custom games should give coins / experience

### ISSUE THREAD

**Issue by popey456963** [Keyma-sh/game-tracker#86]
**Is your feature request related to a problem? Please describe.**
I want to play with my friends, but when I do I don't get to level up or anything.

**Describe the solution you'd like**
XP / Coins should be enabled in customs

**Describe alternatives you've considered**
Not sure.

**Additional context**
I don't see any way of 'gaming' the system in standard custom games.  Restrictions could apply, so, perhaps only 'quotes' and 'random' text could give coins / xp.

**Comment by CameronCT** [comment]
As I mentioned in our DM's that briefly mentions this issue. There is a couple problems that prevent this from being a possibility.

1. Consistency
While adding this feature is relatively easy and simple to do, it's not something that I want to do due to the consistency problem. If I started allowing this to happen for Quotes/Dictionary then people will start bringing up the problems where Custom text should also do the same thing. 

2. Anticheat
A lot of Anticheat measures are disabled in Custom as I don't mind it being used as a sandbox (and it's also good for testing certain changes in the gamplay itself & 1v1 duel).

The only way I could make this work is to add some notice that says "EXP Enabled" and then add information to it, but right now I don't see the use. Especially since I'd have to re-activate some anticheat measures, which for a lot of people that like testing stuff in Custom, might not be too thrilled about.

**Comment by CameronCT** [comment]
Closing this issue due to points above.
