### ISSUE TITLE
Ghost carets should show where other people are in multiplayer

### ISSUE THREAD

**Issue by popey456963** [Keyma-sh/game-tracker#90]
**Is your feature request related to a problem? Please describe.**
I'm frustrated having to look down to see the progress of my opponents.

**Describe the solution you'd like**
Their positions should be more easily visible.  This could be accomplished by giving them a colour and placing a caret of that colour on the screen.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by CameronCT** [comment]
This has been suggested in the past, though not through here but just as a general Discord discussion. A player named ph0t0shop created an extension that allows this ability however I'm not planning on adding it due to the fact it can cause some more resources being used to update the characters.

That's why as of this point the carets for spectators are operating on a capped frames per second rate rather than updating every keystroke.
